# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./QLab_db.h
SOURCES += ./QLab_db.cpp \
    ./main.cpp
FORMS += ./QLab_db.ui
RESOURCES += QLab_db.qrc
